config/routes.rb
Rails.application.routes.draw do

  resources :eventos
  resources :establecimientos
  resources :categoria
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations', passwords: 'users/passwords'}, :path => "", :path_names => {:sign_out => "sign_out", :sign_up => "sign_up"}
  get 'home/index'
  root 'home#index'

  #api
  mount API::Root => '/'
end

app/models/establecimiento.rb
class Establecimiento < ApplicationRecord
  belongs_to :categorium
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/api/v1/establecimientos.rb
module API
  module V1
    class Establecimientos < Grape::API
      resources :establecimientos do
        desc "Lista de establecimientos"
        get do
          Establecimiento.all
        end
        desc "get establecimientos por categoria"
        get do
          est = Establecimiento.where("categorium_id=#{params[:id_category]}")
        end

      end
    end
  end
end

app/controllers/establecimientos_controller.rb
class EstablecimientosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_establecimiento, only: [:show, :edit, :update, :destroy]

  # GET /establecimientos
  # GET /establecimientos.json
  def index
    @establecimientos = Establecimiento.all
  end

  # GET /establecimientos/1
  # GET /establecimientos/1.json
  def show
  end

  # GET /establecimientos/new
  def new
    @establecimiento = Establecimiento.new
  end

  # GET /establecimientos/1/edit
  def edit
  end

  # POST /establecimientos
  # POST /establecimientos.json
  def create
    @establecimiento = Establecimiento.new(establecimiento_params)

    respond_to do |format|
      if @establecimiento.save
        format.html { redirect_to establecimientos_path, notice: 'Establecimiento was successfully created.' }
        format.json { render :show, status: :created, location: @establecimiento }
      else
        format.html { render :new }
        format.json { render json: @establecimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /establecimientos/1
  # PATCH/PUT /establecimientos/1.json
  def update
    respond_to do |format|
      if @establecimiento.update(establecimiento_params)
        format.html { redirect_to establecimientos_path, notice: 'Establecimiento was successfully updated.' }
        format.json { render :show, status: :ok, location: @establecimiento }
      else
        format.html { render :edit }
        format.json { render json: @establecimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /establecimientos/1
  # DELETE /establecimientos/1.json
  def destroy
    @establecimiento.destroy
    respond_to do |format|
      format.html { redirect_to establecimientos_url, notice: 'Establecimiento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_establecimiento
      @establecimiento = Establecimiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def establecimiento_params
      params.require(:establecimiento).permit(:nombre, :numeracion, :alias, :informacion, :latitud, :longitud, :imagen, :categorium_id,:avatar)
    end
end

app/helpers/establecimientos_helper.rb
module EstablecimientosHelper
end

app/views/establecimientos/_form.html.haml
.row
  .col-lg-12
    .panel.panel-primary
      .panel-heading
        Primary Panel
      .panel-body
        = form_for establecimiento,  html: { multipart: true } do |f|
          .col-md-4
            %label.control-label Imagen
            = f.file_field :avatar, class: "file-loading"
          .col-md-8
            .form-group.col-md-6
              %label Nombre
              = f.text_field :nombre, class: "form-control", placeholder: "Introduzca el nombre"
            .form-group.col-md-3
              %label Numeración
              = f.text_field :numeracion, class: "form-control", placeholder: "Introduzca la numeración"
            .form-group.col-md-3
              %label Alias
              = f.text_field :alias, class: "form-control", placeholder: "Introduzca el alias"
            .form-group.col-md-6
              %label Información
              = f.text_field :informacion, class: "form-control", placeholder: "Introduzca la informacion"
            .form-group.col-md-3
              %label Latitud
              = f.text_field :latitud, class: "form-control", placeholder: "Introduzca la latitud"
            .form-group.col-md-3
              %label Longitud
              = f.text_field :longitud, class: "form-control", placeholder: "Introduzca la longitud"

            .form-group.col-md-6
              = f.label "Categoría", class: "control-label"
              = f.select :categorium_id,
                               options_from_collection_for_select(Categorium.all, :id, :nombre, :categorium_id),
                               {},
                               {:class => "form-control contract-customer-holder select2",:id => "select_all_signers",:prompt => "Seleccione una categoría"}


          %div
            = link_to establecimientos_path do
              %i.fa.fa-arrow-left.text-navy Volver
            = f.submit "Guardar", class: "btn btn-sm btn-primary pull-right m-t-n-xs"

:javascript
  $(document).on('ready', function() {
    $("#establecimiento_avatar").fileinput({
      showUpload: true,
      layoutTemplates: {
        main1: "{preview}\n" +
        "<div class=\'input-group {class}\'>\n" +
        "   <div class=\'input-group-btn\'>\n" +
        "       {browse}\n" +
        "       {upload}\n" +
        "       {remove}\n" +
        "   </div>\n" +
        "   {caption}\n" +
        "</div>"
      }
    });
  });

app/views/establecimientos/edit.html.erb
<h1>Editar Establecimiento</h1>

<%= render 'form', establecimiento: @establecimiento %>

app/views/establecimientos/index.html.haml
.row.not-margin
  .col-lg-12.wrapper.border-bottom.white-bg.page-heading
    %h2 Categorias
    %ol.breadcrumb
      %li
        %a{:href => "#{root_path}"} Inicio
      %li.active
        %strong Gestionar Establecimiento

.row
  .col-lg-12
    .ibox.float-e-margins
      .ibox-title
        %h5 Lista de Establecimientos
        .ibox-tools
          %a.collapse-link
            %i.fa.fa-chevron-up
      .ibox-content
        %div
          %span.input-group-btn
            %a.btn.btn-sm.btn-primary{:href => "#{new_establecimiento_path}"} Crear
        %table.table.table-hover
          %thead
            %tr
              %th #
              %th Nombre
              %th Numeración
              %th Alias
              %th Información
              %th Latitud
              %th Longitud
              %th Categoría
              %th Acción
          %tbody
            - i=1;
            - @establecimientos.each do |establecimiento|
              %tr
                %td= i
                %td= establecimiento.nombre
                %td= establecimiento.numeracion
                %td= establecimiento.alias
                %td= establecimiento.informacion
                %td= establecimiento.latitud
                %td= establecimiento.longitud
                %td= establecimiento.categorium.try(:nombre)


                %td
                  = link_to establecimiento do
                    %i.fa.fa-eye.text-navy
                  %a{:href => "#{edit_establecimiento_path(establecimiento)}"}
                    %i.fa.fa-edit.text-navy
                  = link_to establecimiento, method: :delete, data: { confirm: 'Are you sure?' } do
                    %i.fa.fa-trash.text-navy
                - i=i+1

app/views/establecimientos/new.html.haml
.row.not-margin
  .col-lg-12.wrapper.border-bottom.white-bg.page-heading
    %h2 Nuevo establecimiento
    %ol.breadcrumb
      %li
        %a{:href => "#{root_path}"} Inicio
      %li
        Establecimiento
      %li.active
        %strong Nuevo establecimiento

= render 'form', establecimiento: @establecimiento

app/views/establecimientos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @establecimiento.nombre %>
</p>

<p>
  <strong>Numeracion:</strong>
  <%= @establecimiento.numeracion %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @establecimiento.alias %>
</p>

<p>
  <strong>Informacion:</strong>
  <%= @establecimiento.informacion %>
</p>

<p>
  <strong>Latitud:</strong>
  <%= @establecimiento.latitud %>
</p>

<p>
  <strong>Longitud:</strong>
  <%= @establecimiento.longitud %>
</p>

<p>

  <img width="90%" src="<%= @establecimiento.avatar %>">

</p>

<p>
  <strong>Idcategoria:</strong>
  <%= @establecimiento.categorium.nombre %>
</p>

<%= link_to 'Edit', edit_establecimiento_path(@establecimiento) %> |
<%= link_to 'Back', establecimientos_path %>