config/routes.rb
Rails.application.routes.draw do

  resources :eventos
  resources :establecimientos
  resources :categoria
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations', passwords: 'users/passwords'}, :path => "", :path_names => {:sign_out => "sign_out", :sign_up => "sign_up"}
  get 'home/index'
  root 'home#index'

  #api
  mount API::Root => '/'
end

app/models/evento.rb
class Evento < ApplicationRecord
  has_many :multimediums
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:titulo, :contenido, :fecha, :hora)
    end
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/_form.html.haml
.col-lg-4.col-lg-offset-4
  .panel.panel-primary
    .panel-heading
      Primary Panel
    .panel-body
      = form_for(evento) do |f|
        .form-group
          %label Título
          = f.text_field :titulo, class: "form-control", placeholder: "Introduzca el Título"
        .form-group
          %label Contenido
          = f.text_field :contenido, class: "form-control", placeholder: "Introduzca el contenido"
        .form-group
          %label Fecha
          = f.text_field :fecha, class: "form-control", placeholder: "Introduzca la fecha"
        .form-group
          %label Hora
          = f.text_field :hora, class: "form-control", placeholder: "Introduzca la hora"
        %div
          = link_to eventos_path do
            %i.fa.fa-arrow-left.text-navy Volver
          = f.submit "Guardar", class: "btn btn-sm btn-primary pull-right m-t-n-xs"

app/views/eventos/edit.html.erb
<h1>Editar Evento</h1>

<%= render 'form', evento: @evento %>

app/views/eventos/index.html.haml
.row.not-margin
  .col-lg-12.wrapper.border-bottom.white-bg.page-heading
    %h2 Categorias
    %ol.breadcrumb
      %li
        %a{:href => "#{root_path}"} Inicio
      %li.active
        %strong Gestionar Eventos

.row
  .col-lg-12
    .ibox.float-e-margins
      .ibox-title
        %h5 Lista de Eventos
        .ibox-tools
          %a.collapse-link
            %i.fa.fa-chevron-up
      .ibox-content
        %div
          %span.input-group-btn
            %a.btn.btn-sm.btn-primary{:href => "#{new_evento_path}"} Crear
        %table.table.table-hover
          %thead
            %tr
              %th #
              %th Título
              %th Contenido
              %th Fecha
              %th Hora
              %th Acción
          %tbody
            - i=1;
            - @eventos.each do |evento|
              %tr
                %td= i
                %td= evento.titulo
                %td= evento.contenido
                %td= evento.fecha
                %td= evento.hora
                %td
                  = link_to evento do
                    %i.fa.fa-eye.text-navy
                  %a{:href => "#{edit_eevento_path(evento)}"}
                    %i.fa.fa-edit.text-navy
                  = link_to evento, method: :delete, data: { confirm: 'Are you sure?' } do
                    %i.fa.fa-trash.text-navy
                - i=i+1

app/views/eventos/new.html.haml
%h1 Nuevo Evento

= render 'form', evento: @evento

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @evento.titulo %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @evento.contenido %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @evento.fecha %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @evento.hora %>
</p>

<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>