config/routes.rb
Rails.application.routes.draw do

  resources :eventos
  resources :establecimientos
  resources :categoria
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations', passwords: 'users/passwords'}, :path => "", :path_names => {:sign_out => "sign_out", :sign_up => "sign_up"}
  get 'home/index'
  root 'home#index'

  #api
  mount API::Root => '/'
end

app/views/layouts/_footer.html.haml
.footer
  .pull-right
    Santa Cruz
  %div
    %strong Copyright
    UAGRM AR © 2017

app/views/layouts/_menu_header.html.haml
.row.border-bottom
  %nav.navbar.navbar-static-top{:role => "navigation", :style => "margin-bottom: 0"}
    .navbar-header
      %a.navbar-minimalize.minimalize-styl-2.btn.btn-primary{:href => "#"}
        %i.fa.fa-bars
      %form.navbar-form-custom{:action => "search_results.html", :role => "search"}
        .form-group
          %input#top-search.form-control{:name => "top-search", :placeholder => "Buscar...", :type => "text"}/
    %ul.nav.navbar-top-links.navbar-right
      %li
        %span.m-r-sm.text-muted.welcome-message Bienvenido.
      %li.dropdown
        %a.dropdown-toggle.count-info{"data-toggle" => "dropdown", :href => "#"}
          %i.fa.fa-envelope
          %span.label.label-warning 16
        %ul.dropdown-menu.dropdown-messages
          %li
            .dropdown-messages-box
              %a.pull-left{:href => "profile.html"}
                %img.img-circle{:alt => "image", :src => "#{image_path('a7.jpg')}"}
              .media-body
                %small.pull-right 46h ago
                %strong Mike Loreipsum
                started following
                = succeed "." do
                  %strong Monica Smith
                %br/
                %small.text-muted 3 days ago at 7:58 pm - 10.06.2014
          %li.divider
          %li
            .dropdown-messages-box
              %a.pull-left{:href => "profile.html"}
                %img.img-circle{:alt => "image", :src => "#{image_path('a4.jpg')}"}
              .media-body
                %small.pull-right.text-navy 5h ago
                %strong Chris Johnatan Overtunk
                started following
                = succeed "." do
                  %strong Monica Smith
                %br/
                %small.text-muted Yesterday 1:21 pm - 11.06.2014
          %li.divider
          %li
            .dropdown-messages-box
              %a.pull-left{:href => "profile.html"}
                %img.img-circle{:alt => "image", :src => "#{image_path('profile.jpg')}"}
              .media-body
                %small.pull-right 23h ago
                %strong Monica Smith
                love
                = succeed "." do
                  %strong Kim Smith
                %br/
                %small.text-muted 2 days ago at 2:30 am - 11.06.2014
          %li.divider
          %li
            .text-center.link-block
              %a{:href => "mailbox.html"}
                %i.fa.fa-envelope
                %strong Read All Messages
      %li.dropdown
        %a.dropdown-toggle.count-info{"data-toggle" => "dropdown", :href => "#"}
          %i.fa.fa-bell
          %span.label.label-primary 8
        %ul.dropdown-menu.dropdown-alerts
          %li
            %a{:href => "mailbox.html"}
              %div
                %i.fa.fa-envelope.fa-fw
                You have 16 messages
                %span.pull-right.text-muted.small 4 minutes ago
          %li.divider
          %li
            %a{:href => "profile.html"}
              %div
                %i.fa.fa-twitter.fa-fw
                3 New Followers
                %span.pull-right.text-muted.small 12 minutes ago
          %li.divider
          %li
            %a{:href => "grid_options.html"}
              %div
                %i.fa.fa-upload.fa-fw
                Server Rebooted
                %span.pull-right.text-muted.small 4 minutes ago
          %li.divider
          %li
            .text-center.link-block
              %a{:href => "notifications.html"}
                %strong See All Alerts
                %i.fa.fa-angle-right
      %li
        %a{:href => "#{destroy_user_session_path}", "data-method" => :delete}
          %i.fa.fa-sign-out
          Salir

app/views/layouts/_message.html.haml
.sidebard-panel
  %div
    %h4
      Messages
      %span.badge.badge-info.pull-right 16
    .feed-element
      %a.pull-left{:href => "#"}
        %img.img-circle{:alt => "image", :src => "img/a1.jpg"}/
      .media-body
        There are many variations of passages of Lorem Ipsum available.
        %br/
        %small.text-muted Today 4:21 pm
    .feed-element
      %a.pull-left{:href => "#"}
        %img.img-circle{:alt => "image", :src => "img/a2.jpg"}/
      .media-body
        TIt is a long established fact that.
        %br/
        %small.text-muted Yesterday 2:45 pm
    .feed-element
      %a.pull-left{:href => "#"}
        %img.img-circle{:alt => "image", :src => "img/a3.jpg"}/
      .media-body
        Many desktop publishing packages.
        %br/
        %small.text-muted Yesterday 1:10 pm
    .feed-element
      %a.pull-left{:href => "#"}
        %img.img-circle{:alt => "image", :src => "img/a4.jpg"}/
      .media-body
        The generated Lorem Ipsum is therefore always free.
        %br/
        %small.text-muted Monday 8:37 pm
  .m-t-md
    %h4 Statistics
    %p
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.
    .row.m-t-sm
      .col-md-6
        %span.bar 5,3,9,6,5,9,7,3,5,2
        %h5
          %strong 169
          Posts
      .col-md-6
        %span.line 5,3,9,6,5,9,7,3,5,2
        %h5
          %strong 28
          Orders
  .m-t-md
    %h4 Discussion
    %div
      %ul.list-group
        %li.list-group-item
          %span.badge.badge-primary 16
          General topic
        %li.list-group-item
          %span.badge.badge-info 12
          The generated Lorem
        %li.list-group-item
          %span.badge.badge-warning 7
          There are many variations

app/views/layouts/_sidebar.html.haml
%nav.navbar-default.navbar-static-side.boxshadow-none{:role => "navigation"}
  .sidebar-collapse
    %ul#side-menu.nav.metismenu
      %li.nav-header
        .dropdown.profile-element
          %span
            %img.img-circle{:alt => "image", :src => "#{image_path('profile_small.jpg')}"}
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %span.clear
              %span.block.m-t-xs
                %strong.font-bold David Williams
              %span.text-muted.text-xs.block
                Art Director
                %b.caret
          %ul.dropdown-menu.animated.fadeInRight.m-t-xs
            %li
              %a{:href => "profile.html"} Perfil
            %li
              %a{:href => "contacts.html"} Contactos
            %li
              %a{:href => "mailbox.html"} Mailbox
            %li.divider
            %li
              %a{:href => "#{destroy_user_session_path}", "data-method" => :delete} Salir
        .logo-element
          IN+
      %li.active
        %a{:href => "#{root_path}"}
          %i.fa.fa-dashboard
          %span.nav-label Inicio
      %li
        %a{:href => "layouts.html"}
          %i.fa.fa-users
          %span.nav-label Usuarios
      %li
        %a{:href => "#{categoria_path}"}
          %i.fa.fa-th-large
          %span.nav-label Categoria
      %li
        %a{:href => "#{establecimientos_path}"}
          %i.fa.fa-bank
          %span.nav-label Establecimientos
      %li
        %a{:href => "#{eventos_path}"}
          %i.fa.fa-newspaper-o
          %span.nav-label Eventos

app/views/layouts/_sidebar_right.html.haml
#right-sidebar
  .sidebar-container
    %ul.nav.nav-tabs.navs-3
      %li.active
        %a{"data-toggle" => "tab", :href => "#tab-1"}
          Notes
      %li
        %a{"data-toggle" => "tab", :href => "#tab-2"}
          Projects
      %li
        %a{"data-toggle" => "tab", :href => "#tab-3"}
          %i.fa.fa-gear
    .tab-content
      #tab-1.tab-pane.active
        .sidebar-title
          %h3
            %i.fa.fa-comments-o
            Latest Notes
          %small
            %i.fa.fa-tim
            You have 10 new message.
        %div
          .sidebar-message
            %a{:href => "#"}
              .pull-left.text-center
                %img.img-circle.message-avatar{:alt => "image", :src => "#{image_path('a1.jpg')}"}
                .m-t-xs
                  %i.fa.fa-star.text-warning
                  %i.fa.fa-star.text-warning
              .media-body
                There are many variations of passages of Lorem Ipsum available.
                %br/
                %small.text-muted Today 4:21 pm
          .sidebar-message
            %a{:href => "#"}
              .pull-left.text-center
                %img.img-circle.message-avatar{:alt => "image", :src => "#{image_path('a2.jpg')}"}
              .media-body
                The point of using Lorem Ipsum is that it has a more-or-less normal.
                %br/
                %small.text-muted Yesterday 2:45 pm
          .sidebar-message
            %a{:href => "#"}
              .pull-left.text-center
                %img.img-circle.message-avatar{:alt => "image", :src => "#{image_path('a3.jpg')}"}
                .m-t-xs
                  %i.fa.fa-star.text-warning
                  %i.fa.fa-star.text-warning
                  %i.fa.fa-star.text-warning
              .media-body
                Mevolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
                %br/
                %small.text-muted Yesterday 1:10 pm
          .sidebar-message
            %a{:href => "#"}
              .pull-left.text-center
                %img.img-circle.message-avatar{:alt => "image", :src => "#{image_path('a4.jpg')}"}
              .media-body
                Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the
                %br/
                %small.text-muted Monday 8:37 pm
          .sidebar-message
            %a{:href => "#"}
              .pull-left.text-center
                %img.img-circle.message-avatar{:alt => "image", :src => "#{image_path('a8.jpg')}"}
              .media-body
                All the Lorem Ipsum generators on the Internet tend to repeat.
                %br/
                %small.text-muted Today 4:21 pm
          .sidebar-message
            %a{:href => "#"}
              .pull-left.text-center
                %img.img-circle.message-avatar{:alt => "image", :src => "#{image_path('a7.jpg')}"}
              .media-body
                Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
                %br/
                %small.text-muted Yesterday 2:45 pm
          .sidebar-message
            %a{:href => "#"}
              .pull-left.text-center
                %img.img-circle.message-avatar{:alt => "image", :src => "#{image_path('a3.jpg')}"}
                .m-t-xs
                  %i.fa.fa-star.text-warning
                  %i.fa.fa-star.text-warning
                  %i.fa.fa-star.text-warning
              .media-body
                The standard chunk of Lorem Ipsum used since the 1500s is reproduced below.
                %br/
                %small.text-muted Yesterday 1:10 pm
          .sidebar-message
            %a{:href => "#"}
              .pull-left.text-center
                %img.img-circle.message-avatar{:alt => "image", :src => "#{image_path('a4.jpg')}"}
              .media-body
                Uncover many web sites still in their infancy. Various versions have.
                %br/
                %small.text-muted Monday 8:37 pm
      #tab-2.tab-pane
        .sidebar-title
          %h3
            %i.fa.fa-cube
            Latest projects
          %small
            %i.fa.fa-tim
            You have 14 projects. 10 not completed.
        %ul.sidebar-list
          %li
            %a{:href => "#"}
              .small.pull-right.m-t-xs 9 hours ago
              %h4 Business valuation
              It is a long established fact that a reader will be distracted.
              .small Completion with: 22%
              .progress.progress-mini
                .progress-bar.progress-bar-warning{:style => "width: 22%;"}
              .small.text-muted.m-t-xs Project end: 4:00 pm - 12.06.2014
          %li
            %a{:href => "#"}
              .small.pull-right.m-t-xs 9 hours ago
              %h4 Contract with Company
              Many desktop publishing packages and web page editors.
              .small Completion with: 48%
              .progress.progress-mini
                .progress-bar{:style => "width: 48%;"}
          %li
            %a{:href => "#"}
              .small.pull-right.m-t-xs 9 hours ago
              %h4 Meeting
              By the readable content of a page when looking at its layout.
              .small Completion with: 14%
              .progress.progress-mini
                .progress-bar.progress-bar-info{:style => "width: 14%;"}
          %li
            %a{:href => "#"}
              %span.label.label-primary.pull-right NEW
              %h4 The generated
              / <div class="small pull-right m-t-xs">9 hours ago</div>
              There are many variations of passages of Lorem Ipsum available.
              .small Completion with: 22%
              .small.text-muted.m-t-xs Project end: 4:00 pm - 12.06.2014
          %li
            %a{:href => "#"}
              .small.pull-right.m-t-xs 9 hours ago
              %h4 Business valuation
              It is a long established fact that a reader will be distracted.
              .small Completion with: 22%
              .progress.progress-mini
                .progress-bar.progress-bar-warning{:style => "width: 22%;"}
              .small.text-muted.m-t-xs Project end: 4:00 pm - 12.06.2014
          %li
            %a{:href => "#"}
              .small.pull-right.m-t-xs 9 hours ago
              %h4 Contract with Company
              Many desktop publishing packages and web page editors.
              .small Completion with: 48%
              .progress.progress-mini
                .progress-bar{:style => "width: 48%;"}
          %li
            %a{:href => "#"}
              .small.pull-right.m-t-xs 9 hours ago
              %h4 Meeting
              By the readable content of a page when looking at its layout.
              .small Completion with: 14%
              .progress.progress-mini
                .progress-bar.progress-bar-info{:style => "width: 14%;"}
          %li
            %a{:href => "#"}
              %span.label.label-primary.pull-right NEW
              %h4 The generated
              / <div class="small pull-right m-t-xs">9 hours ago</div>
              There are many variations of passages of Lorem Ipsum available.
              .small Completion with: 22%
              .small.text-muted.m-t-xs Project end: 4:00 pm - 12.06.2014
      #tab-3.tab-pane
        .sidebar-title
          %h3
            %i.fa.fa-gears
            Settings
          %small
            %i.fa.fa-tim
            You have 14 projects. 10 not completed.
        .setings-item
          %span
            Show notifications
          .switch
            .onoffswitch
              %input#example.onoffswitch-checkbox{:name => "collapsemenu", :type => "checkbox"}/
              %label.onoffswitch-label{:for => "example"}
                %span.onoffswitch-inner
                %span.onoffswitch-switch
        .setings-item
          %span
            Disable Chat
          .switch
            .onoffswitch
              %input#example2.onoffswitch-checkbox{:checked => "checked", :name => "collapsemenu", :type => "checkbox"}/
              %label.onoffswitch-label{:for => "example2"}
                %span.onoffswitch-inner
                %span.onoffswitch-switch
        .setings-item
          %span
            Enable history
          .switch
            .onoffswitch
              %input#example3.onoffswitch-checkbox{:name => "collapsemenu", :type => "checkbox"}/
              %label.onoffswitch-label{:for => "example3"}
                %span.onoffswitch-inner
                %span.onoffswitch-switch
        .setings-item
          %span
            Show charts
          .switch
            .onoffswitch
              %input#example4.onoffswitch-checkbox{:name => "collapsemenu", :type => "checkbox"}/
              %label.onoffswitch-label{:for => "example4"}
                %span.onoffswitch-inner
                %span.onoffswitch-switch
        .setings-item
          %span
            Offline users
          .switch
            .onoffswitch
              %input#example5.onoffswitch-checkbox{:checked => "checked", :name => "collapsemenu", :type => "checkbox"}/
              %label.onoffswitch-label{:for => "example5"}
                %span.onoffswitch-inner
                %span.onoffswitch-switch
        .setings-item
          %span
            Global search
          .switch
            .onoffswitch
              %input#example6.onoffswitch-checkbox{:checked => "checked", :name => "collapsemenu", :type => "checkbox"}/
              %label.onoffswitch-label{:for => "example6"}
                %span.onoffswitch-inner
                %span.onoffswitch-switch
        .setings-item
          %span
            Update everyday
          .switch
            .onoffswitch
              %input#example7.onoffswitch-checkbox{:name => "collapsemenu", :type => "checkbox"}/
              %label.onoffswitch-label{:for => "example7"}
                %span.onoffswitch-inner
                %span.onoffswitch-switch
        .sidebar-content
          %h4 Settings
          .small
            I belive that. Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            And typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
            Over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title .:: UAGRM AR WEB ::.
    = csrf_meta_tags
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", :name => "viewport"}/
    %meta{:content => "width=device-width", :name => "viewport"}/

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  -if !user_signed_in?
    %body.gray-bg
      = yield
  -else
    %body.md-skin
      #wrapper
        = render 'layouts/sidebar'
        #page-wrapper.gray-bg.dashoard-1
          = render 'layouts/menu_header'
          .wrapper.wrapper-content.animated.fadeInRight
            = yield
          = render "layouts/footer"
          = render "layouts/sidebar_right"